use loggit::logger::set_log_level;
use loggit::Level;
use melodic_music_mixing::algorithm::melodic_sort;
use melodic_music_mixing::pipeline::analyze_and_sort_tracks;
use melodic_music_mixing::types::track::Track;

fn main() {
    sort_jan_2026();
}

fn sort_jan_2026() {
    let track_paths: Vec<std::path::PathBuf> = vec![
        "/Users/dobbikov/Desktop/djmusic/1-3xil3-Outblow-7BY1IX.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-A-M-C-Bass--Teddy-Kil-TGOTOI.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-A-M-C-Operator--Junk--U8L5RM.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-A-Way-Half-Life-3-L5EGWF.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Abis-Grains-Of-Suna-KUM5NA.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Absu-NTQL--Shmidoo-Ragnarok-XWFIHU.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Absu-NTQL-Broken-EEKRF9.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Absu-NTQL-Temple--Ekwols-Remix--4J12V5.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Absu-NTQL-Urusai-PTXCU5.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Audio-Blood-On-Our-Ha-TZAZ35.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Audio-Disruptive--Bur-D9ZOK7.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Audio-Don-t-Play-X5VKYU.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Audio-Genesis-Device--KFCQU0.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-BADVOID-CAUTION-47SHEJ.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Black-Sun-Empire-Steppenwolf-7QUXE6.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Black-Sun-Empire-Steppenwolf-RC6MPP.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Burr-Oak-Far-From-Home-Q8E91I.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Burr-Oak-Ground---Pound-FJWXDL.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Burr-Oak-Life-Is-Lost-C85KHI.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Burr-Oak-Shinigami-RR4UDH.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Burr-Oak-Shinigami-VIP-0DP3BX.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Burr-Oak-Shinigami-VIP-12GZV3.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Burr-Oak-Time-Has-Come-PKN3H2.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Cyntax-Eat-It-A9A1QW.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Cyntax-Face-Pound-HFYXDF.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Cyntax-Your-Time-Is-No-SPQOWI.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Despersion-Everything--VIP-6EDMO2.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Despersion-Show-Me-JJE1VB.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Diode-SKNK-JMWUGY.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Disphonia-Entropy-BPO1FQ.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Ekwols-Drowning-Q9SW98.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Ekwols-Hyena-OCEHA2.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Ekwols-Shadows-Black-H9TO36.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Eluun-Glassy-Star-QZ875G.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Erb-n-Dub-Loud-Mouth--Dis-8RT44Q.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Finalfix-Arrival-0NWV0L.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Finalfix-Cerberus-577BSO.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Finalfix-Hydraulic-W5BCCT.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Finalfix-Hypocrites--Joe-LVEA2R.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Finalfix-With-You--Final-5KJPDU.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-First-Person-Disconnected-So-OQWAET.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Futura-Boombox-This-Is-Our-Fut-L88GAZ.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Gancher-Blood-Money-VTK2P7.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Gancher-Chemtrail-LSRXC2.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Gancher-Courage-RR6LY0.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Gancher-Flat-Earth-D0CO04.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Gancher-Gangsta-U0X666.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Gancher-Interceptor-50WNVE.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Gancher-Kickback-UZ1JUT.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Gancher-PSYOP-3JF4K1.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Gancher-Rituals-6V21KS.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Gancher-Wake-Up-OUTVPC.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Gancher-Watch-Me-IX7CTS.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Gexan-Time-Tick-PL3I2M.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Gydra-Caravan-OJTLT7.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Gydra-Ikra--Jade-Veno-0UJ106.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Gydra-Lava-Run-BBKKJ1.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Gydra-Solar-Eclipse-CO6Q4T.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-HighThere-Depart-The-Ends-MTAW7S.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-HighThere-Prisoner-SMCKQ8.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Holotrope-Corridor-Pulse--DZQB1P.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Holotrope-Evacuation-ZABAJW.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Joe-Ford-Sunfall-1QL0J4.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Karpa-Serpent-JEWPDR.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Killbox-Bound-to-Others-SZO4YP.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Killbox-Ultimatum-5RE7FC.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Magnetude-Goodbye-UMX866.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Magnetude-I-Want-You-C037HZ.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Magnetude-I-m-For-You-MGYOXK.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Magnetude-Still-There-ZICEFO.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Magnetude-The-Star-BGLAFQ.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Magnetude-The-Star-BMA6GP.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Mean-Teeth-Shut-Them-Down--VGT5GB.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Mizo-Katana-PAVDBG.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Mizo-Mechanical-Paw--57HQ38.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Mob-Tactics-Dirtgrub-HRM4XH.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Mr--Frenkie-Bass-Symptom--A-9E0JHW.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Nuvertal-Combat-Sword-KHLQ2H.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Nuvertal-Nine-PPD2V0.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Omneum-Avenoir-4VHGH0.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Omneum-Cybernetic-Modu-4EME08.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Omneum-Deep-Dive-ITUS2G.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Omneum-Resonance--Audi-0KRXJ6.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Opsen-D-cadence-64P7L3.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Opsen-Give-Them-Hell-MHL02B.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Overtune-Nothing-Will-Su-ONNFHP.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Ovtlier-Warriors--Remix-8SWI13.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-PAPERCLIP-Kernel--Origina-NDXSYK.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-PAPERCLIP-Misterio-N4H5NR.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-PAPERCLIP-Гагарин-WP37X2.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Phenom-Goblin-WJAZCR.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Prolix-Dynamite-NW1ARR.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Prolix-Savages--Finalf-T6AECF.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Pythius-Erase-Me--Burr--7NAWIU.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Pythius-In-My-Head--Hys-42QTTE.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-QO-Get-Wild-HQ16RC.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-SLWDWN-The-Rift--Darks-T9JQEN.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-STATE-OF-MIND-Red-Sky-R3LRXN.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Silent-Extent-Falling-Down--F-79QXH8.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Sindicate-Listen-Up-LD7BTL.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Skellytn-Breaking-Point-0MX6HA.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Skellytn-Keys-To-The-Rav-KM59A4.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Submonitor-Let-Go-XKXWN0.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Submonitor-The-Light-CPAPBF.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-TR-Tactics-Halloween-VIP-TXEYFZ.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-TR-Tactics-Shrouded-P3UOH2.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Task-Horizon-Astroturf-HL8MRQ.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Task-Horizon-Mindfragger--SL-TWYO47.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Tayn-Nebula-Groove-CATF2A.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-The-Clamps-From-Dust-To-Da-X0V2VH.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Tobax-Heidelore-IDQHY8.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Tokkobana-Wake-Up--Ganche-60J3TY.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Transforma-Ghouls-H1LDIJ.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Transforma-Quantum-Leap--O-50Y20J.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Transforma-Well-Oiled-Mach-05NZ1S.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-TriaMer-Bastards--Original-Mix--DXRLRN.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Volatile-Cycle-Alone-VS7G57.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Zigi-SC-Dementor-80D03G.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Zigi-SC-Stepper--Balron-W3IQJD.mp3",
        "/Users/dobbikov/Desktop/djmusic/1-Zombie-Cats-Hellcat-29GQDX.mp3",
        "/Users/dobbikov/Desktop/djmusic/10-Akov-Snake-Eater--AK-1GTLCV.mp3",
        "/Users/dobbikov/Desktop/djmusic/10-Desimal-Afterlife-VRQOE3.mp3",
        "/Users/dobbikov/Desktop/djmusic/10-Gancher-Where-Are-You-9OQXHI.mp3",
        "/Users/dobbikov/Desktop/djmusic/10-Manuel-Orta-Popurr--Rociero-HP3NBX.mp3",
        "/Users/dobbikov/Desktop/djmusic/10-Mind-freqnz-Tralalero-Trala-E6V80U.mp3",
        "/Users/dobbikov/Desktop/djmusic/10-Mind-freqnz-Tralalero-Tralala-Q7OH9J.mp3",
        "/Users/dobbikov/Desktop/djmusic/10-Neonlight-Denunziant--Fin-HR5M9P.mp3",
        "/Users/dobbikov/Desktop/djmusic/11-Celldweller-Shapeshifter--Z-80QNGX.mp3",
        "/Users/dobbikov/Desktop/djmusic/11-Cyntax-Pericardium-HFXNAQ.mp3",
        "/Users/dobbikov/Desktop/djmusic/11-Joe-Ford-Tomb-Raver-44C7UR.mp3",
        "/Users/dobbikov/Desktop/djmusic/11-Redpill-Interlinked-8QIXOT.mp3",
        "/Users/dobbikov/Desktop/djmusic/12-Pythius-Sovereign--Neon-G5Z0A0.mp3",
        "/Users/dobbikov/Desktop/djmusic/12-The-Clamps-Click-Clack-0JZYVJ.mp3",
        "/Users/dobbikov/Desktop/djmusic/13-Burr-Oak-Criminal-Romanc-VFIW6D.mp3",
        "/Users/dobbikov/Desktop/djmusic/13-Finalfix-Apocalypse-ZVB1DB.mp3",
        "/Users/dobbikov/Desktop/djmusic/13-The-Clamps-Snakes---Coward-RST00B.mp3",
        "/Users/dobbikov/Desktop/djmusic/14-Burr-Oak-All-I-Dream-GLCSRN.mp3",
        "/Users/dobbikov/Desktop/djmusic/14-The-Clamps-The-Bill-EWPYL9.mp3",
        "/Users/dobbikov/Desktop/djmusic/15-Submonitor-Right-Now-87CYUT.mp3",
        "/Users/dobbikov/Desktop/djmusic/16-5-NIZZA-Пятница-9EPA6R.mp3",
        "/Users/dobbikov/Desktop/djmusic/16-Burr-Oak-Save-These-Days-SW86RA.mp3",
        "/Users/dobbikov/Desktop/djmusic/17-Burr-Oak-Reaper-JSX8ZK.mp3",
        "/Users/dobbikov/Desktop/djmusic/17-Meph-Dystopian-A61ZVX.mp3",
        "/Users/dobbikov/Desktop/djmusic/1731677031_Pythius_Wide_Awake_ft_flowanastasia_Prolix_Remix.mp3",
        "/Users/dobbikov/Desktop/djmusic/18-Burr-Oak-Somewhere-We-Be-4OSJBK.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Absu-NTQL-Conclusion-VIP-C8W7W0.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Absu-NTQL-Shards-E4WR1Z.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Absu-NTQL-Temple-LZ45W6.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Agressor-Bunx-Vibrations-F9NAKN.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-BADVOID-KEEP-IT-HARDCOR-M0ZCH6.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Blur-Song-2-L32XZT.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Burr-Oak-Originate-J35FPR.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Burr-Oak-Strafe-UFPKAZ.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Burr-Oak-Symbolic-9ZDRZM.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Cyntax-Darkness-Surrou-IVXXIU.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Cyntax-Machines-Z11XHJ.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Despersion-Peace-DUDFZG.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Dom---Roland-Tone-Poem-W807MB.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Dropset-Ignition-D444J5.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Finalfix-Idle-Hands-GFGCI8.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Finalfix-Melting-Pot-CCHMIC.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Finalfix-Out-of-Place-N1MPUA.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Gancher-5G-DXA7TO.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Gydra-Noise-Of-The-Ma-XXP9Y6.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Impex-Sin-Sister-G4PCQ1.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Joe-Ford-Into-Black-969QUX.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Kevala-Simulated-Freed-I7RBJM.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Mean-Teeth-3-Minutes--TR-T-O3HJXS.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Meph-Ironforge-OZ57FN.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Mizo-Dust-Devil-7FLCF6.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Mizo-Harder-KZHQUH.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Noisia-Anomaly-PRLCN6.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Omneum-Correspondence-M9CAE6.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Omneum-Psi-Reaver-LXBNDD.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Omneum-Resonance-KL8JM3.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Omneum-Thorns-Y4VUDS.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-PAPERCLIP-Vacuum-OI3M0J.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Prolix-The-Message-VIP-6C1GWZ.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Punchman-Biceps-Gun-1T7E61.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Pythius-Tarkin-GSRP5Z.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Raido-Breakdown-81K8YJ.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Redpill-The-Chase-UOAUXQ.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Sam-Foxx-Nuke-EWY8Q9.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Sindicate-Smack-In-The-Fa-X8E0OD.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Sinister-Souls-Never-2-Late-XGI2F0.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-TR-Tactics-Against-The-Gra-YD2OE0.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-TR-Tactics-Sound-Gun-RU9R3A.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-TRCD-Deep-Vision--Bi-UKIX6I.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Task-Horizon-Wire-Head-ZC94YU.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-The-Clamps-Les-Autres-JN1RFF.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Transforma-It-Came-From-Th-BZNGVM.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Zombie-Cats-Hard-Spin-418F1H.mp3",
        "/Users/dobbikov/Desktop/djmusic/2-Zombie-Cats-Hellcat--Tanuki-JAHVOB.mp3",
        "/Users/dobbikov/Desktop/djmusic/20-Killbox-Epicentre-3GE2QZ.mp3",
        "/Users/dobbikov/Desktop/djmusic/20-TR-Tactics-Weak-VIP-TFIQTZ.mp3",
        "/Users/dobbikov/Desktop/djmusic/22-Metanoia-The-Edge-RT4856.mp3",
        "/Users/dobbikov/Desktop/djmusic/22-Xylym-Black-Hole-Heav-KNID7E.mp3",
        "/Users/dobbikov/Desktop/djmusic/26-Finalfix-End-Of-Days-L7SC3D.mp3",
        "/Users/dobbikov/Desktop/djmusic/27-Nuvertal-In-My-Head-6WOBW8.mp3",
        "/Users/dobbikov/Desktop/djmusic/3-Absu-NTQL-Summon-5PTE9T.mp3",
        "/Users/dobbikov/Desktop/djmusic/3-Despersion-Offensive-4KMV33.mp3",
        "/Users/dobbikov/Desktop/djmusic/3-Emperor-I-Was-XIORSD.mp3",
        "/Users/dobbikov/Desktop/djmusic/3-Finalfix-Hope-Is-Lost-N8EH2S.mp3",
        "/Users/dobbikov/Desktop/djmusic/3-Finalfix-The-Forbidden-F-R0EOSB.mp3",
        "/Users/dobbikov/Desktop/djmusic/3-Finalfix-Under-My-Skin-K15AP3.mp3",
        "/Users/dobbikov/Desktop/djmusic/3-Holotrope-Converted-QEU3EK.mp3",
        "/Users/dobbikov/Desktop/djmusic/3-Mizo-The-Pursuit-1T829Z.mp3",
        "/Users/dobbikov/Desktop/djmusic/3-Nuvertal-Sharp-60V4PZ.mp3",
        "/Users/dobbikov/Desktop/djmusic/3-Nuvertal-The-Cure-PGTBCH.mp3",
        "/Users/dobbikov/Desktop/djmusic/3-Raido-Hold-It-Down-4340N9.mp3",
        "/Users/dobbikov/Desktop/djmusic/3-Redpill-Air-Strike-8NX5R1.mp3",
        "/Users/dobbikov/Desktop/djmusic/3-Redpill-Executionist--B-RHI9B7.mp3",
        "/Users/dobbikov/Desktop/djmusic/3-Sinister-Souls-Alive-VA0HZ6.mp3",
        "/Users/dobbikov/Desktop/djmusic/3-Sinister-Souls-Ultimatum--Meri-631V6T.mp3",
        "/Users/dobbikov/Desktop/djmusic/3-Skrimor-Soul-Splitters-IIFXGH.mp3",
        "/Users/dobbikov/Desktop/djmusic/3-Submonitor-Biologica-12M3F7.mp3",
        "/Users/dobbikov/Desktop/djmusic/3-TR-Tactics-Facebreaker-RXB8B0.mp3",
        "/Users/dobbikov/Desktop/djmusic/3-The-Clamps-Where-Secrets-L-X0VIQ4.mp3",
        "/Users/dobbikov/Desktop/djmusic/3-Zigi-SC-Childsplay-T92K6T.mp3",
        "/Users/dobbikov/Desktop/djmusic/4-A-M-C-Bass-V4QLSW.mp3",
        "/Users/dobbikov/Desktop/djmusic/4-Absu-NTQL-Ritual-Impulse-F286MU.mp3",
        "/Users/dobbikov/Desktop/djmusic/4-Burr-Oak-All-Alone-ZFDMAF.mp3",
        "/Users/dobbikov/Desktop/djmusic/4-Burr-Oak-J-laisse-Des-Tr-EB4HRI.mp3",
        "/Users/dobbikov/Desktop/djmusic/4-Finalfix-Forsaken-UR5DD8.mp3",
        "/Users/dobbikov/Desktop/djmusic/4-Finalfix-Purgatory-B7QMLQ.mp3",
        "/Users/dobbikov/Desktop/djmusic/4-Finalfix-The-Prophecy-7XPQW4.mp3",
        "/Users/dobbikov/Desktop/djmusic/4-Magnetude-Broken-Y50TIV.mp3",
        "/Users/dobbikov/Desktop/djmusic/4-Merikan-Altered-States-XWGBKY.mp3",
        "/Users/dobbikov/Desktop/djmusic/4-Merikan-Black-Antilope-NSECEF.mp3",
        "/Users/dobbikov/Desktop/djmusic/4-Misanthrop-Alert-U5WNL2.mp3",
        "/Users/dobbikov/Desktop/djmusic/4-Omneum-Blade-Dance-FZOY54.mp3",
        "/Users/dobbikov/Desktop/djmusic/4-PAPERCLIP-Velorok-H8RPMZ.mp3",
        "/Users/dobbikov/Desktop/djmusic/4-PAPERCLIP-Vitamin-A--Orig-28L661.mp3",
        "/Users/dobbikov/Desktop/djmusic/4-Skellytn-Oracle-Protocol-SXTUX0.mp3",
        "/Users/dobbikov/Desktop/djmusic/4-TR-Tactics-New-Danger-FMS9UJ.mp3",
        "/Users/dobbikov/Desktop/djmusic/5-5-NIZZA-It-s-not-over-n-DPPK1R.mp3",
        "/Users/dobbikov/Desktop/djmusic/5-A-Cray-Anvil-KEEEKI.mp3",
        "/Users/dobbikov/Desktop/djmusic/5-Audio-Rave-Machine-8HD0BM.mp3",
        "/Users/dobbikov/Desktop/djmusic/5-Gydra-Noise-Of-The-Ma-QXLN9Y.mp3",
        "/Users/dobbikov/Desktop/djmusic/5-Mizo-Rage-Out-ELB2RA.mp3",
        "/Users/dobbikov/Desktop/djmusic/5-Omneum-Liminal-Visions-YI8688.mp3",
        "/Users/dobbikov/Desktop/djmusic/5-Raido-Evil-Eye-5H2HP6.mp3",
        "/Users/dobbikov/Desktop/djmusic/5-Redpill-Flash-Point--Me-560171.mp3",
        "/Users/dobbikov/Desktop/djmusic/5-The-Clamps-Faith-QF92PL.mp3",
        "/Users/dobbikov/Desktop/djmusic/6-Burr-Oak-Do-Androids-Dre-R13SFY.mp3",
        "/Users/dobbikov/Desktop/djmusic/6-Gancher-ARRIVAL-X7WHXV.mp3",
        "/Users/dobbikov/Desktop/djmusic/6-Neonlight-Triumph--Burr-O-UJYDCG.mp3",
        "/Users/dobbikov/Desktop/djmusic/6-Redpill-Slap-The-Bassli-FP8HDO.mp3",
        "/Users/dobbikov/Desktop/djmusic/7-Audio-Bedlam-Axis--TR-X243HA.mp3",
        "/Users/dobbikov/Desktop/djmusic/7-Gydra-Om-PWZXF0.mp3",
        "/Users/dobbikov/Desktop/djmusic/7-Ihr-Kiku-AFOLHM.mp3",
        "/Users/dobbikov/Desktop/djmusic/7-Irontype-Shot-Down-0URY7O.mp3",
        "/Users/dobbikov/Desktop/djmusic/7-Noisia-Mantra-3U5AZ7.mp3",
        "/Users/dobbikov/Desktop/djmusic/7-Redpill-Flesh---Blood-MJEZ45.mp3",
        "/Users/dobbikov/Desktop/djmusic/9-Current-Value-Triple-J2UQGF.mp3",
        "/Users/dobbikov/Desktop/djmusic/99d283cf09b2.mp3 extra=0Qz5KVeb1s",
        "/Users/dobbikov/Desktop/djmusic/A.M.C  Turno-Draw 4 That.mp3",
        "/Users/dobbikov/Desktop/djmusic/Akrom, Inward, Hanzo, Randie-Berserk.mp3",
        "/Users/dobbikov/Desktop/djmusic/Arcade   Magnetude.mp3",
        "/Users/dobbikov/Desktop/djmusic/Burr Oak-Originate.mp3",
        "/Users/dobbikov/Desktop/djmusic/Burr Oak-Revenge.mp3",
        "/Users/dobbikov/Desktop/djmusic/Coman Dante-Rally.mp3",
        "/Users/dobbikov/Desktop/djmusic/Current Value, Cooh-Reket.mp3",
        "/Users/dobbikov/Desktop/djmusic/DA BASS  Akrom-Mamba.mp3",
        "/Users/dobbikov/Desktop/djmusic/DRUM AND BASS #4.mp3",
        "/Users/dobbikov/Desktop/djmusic/Delta Heavy-Gargantua.mp3",
        "/Users/dobbikov/Desktop/djmusic/Despersion-December.mp3",
        "/Users/dobbikov/Desktop/djmusic/Dub Elements feat. 20Hz Audio-Get On.mp3",
        "/Users/dobbikov/Desktop/djmusic/Ekwols-Nervous.mp3",
        "/Users/dobbikov/Desktop/djmusic/Entr acte (320)   Magnetude.mp3",
        "/Users/dobbikov/Desktop/djmusic/Friday   Magnetude.mp3",
        "/Users/dobbikov/Desktop/djmusic/Gancher_ _Ruin-Erase.mp3",
        "/Users/dobbikov/Desktop/djmusic/Hallucinator,_Gridlok-No_Escape.mp3",
        "/Users/dobbikov/Desktop/djmusic/Inward, Hanzo, Randie-Bloom.mp3",
        "/Users/dobbikov/Desktop/djmusic/Jade-Lazer Tag (Neonlight remix).mp3",
        "/Users/dobbikov/Desktop/djmusic/Joe Ford-The End.mp3",
        "/Users/dobbikov/Desktop/djmusic/Knoxz-Inferno.mp3",
        "/Users/dobbikov/Desktop/djmusic/Magnetude - Goodbye.flac",
        "/Users/dobbikov/Desktop/djmusic/Magnetude - Goodbye.mp3",
        "/Users/dobbikov/Desktop/djmusic/Magnetude-Broken.mp3",
        "/Users/dobbikov/Desktop/djmusic/Magnetude-Now_Run.mp3",
        "/Users/dobbikov/Desktop/djmusic/Magnetude-Trail of Tears.mp3",
        "/Users/dobbikov/Desktop/djmusic/Mantis   Magnetude.mp3",
        "/Users/dobbikov/Desktop/djmusic/Mark Instinct-CTRL (Original Mix).(AGRMusic).mp3",
        "/Users/dobbikov/Desktop/djmusic/Mean Teeth-Stormer.mp3",
        "/Users/dobbikov/Desktop/djmusic/Mean_Teeth-Multitude.mp3",
        "/Users/dobbikov/Desktop/djmusic/Merikan  IHR-Nocturno.mp3",
        "/Users/dobbikov/Desktop/djmusic/Merikan - Absolute Zero.flac",
        "/Users/dobbikov/Desktop/djmusic/Merikan - Black Antilope.flac",
        "/Users/dobbikov/Desktop/djmusic/Merikan - Evideon.flac",
        "/Users/dobbikov/Desktop/djmusic/Merikan - Vektor.flac",
        "/Users/dobbikov/Desktop/djmusic/Merikan - Witch Hunter.flac",
        "/Users/dobbikov/Desktop/djmusic/Merikan-Converge.mp3",
        "/Users/dobbikov/Desktop/djmusic/Merikan-Infobesity.mp3",
        "/Users/dobbikov/Desktop/djmusic/Merikan-Untameable 180 BPM.mp3",
        "/Users/dobbikov/Desktop/djmusic/Mizo-Icy Wyrm.mp3",
        "/Users/dobbikov/Desktop/djmusic/Mizo-Icy_Wyrm.mp3",
        "/Users/dobbikov/Desktop/djmusic/Myselor-Funky Shit.mp3",
        "/Users/dobbikov/Desktop/djmusic/Neonlight-Bad_Omen.mp3",
        "/Users/dobbikov/Desktop/djmusic/Nitepunk-Miracle (REAPER Remix).mp3",
        "/Users/dobbikov/Desktop/djmusic/Prolix, DC Breaks-Infinity VIP.mp3",
        "/Users/dobbikov/Desktop/djmusic/Pythius, Dj Hidden-Corrosive.mp3",
        "/Users/dobbikov/Desktop/djmusic/Pythius-Abandon.mp3",
        "/Users/dobbikov/Desktop/djmusic/Pythius-Haymaker.mp3",
        "/Users/dobbikov/Desktop/djmusic/QO_ _Trilo-Push_It_To_The_Limit.mp3",
        "/Users/dobbikov/Desktop/djmusic/Receptor-Lullaby (Original mix) DnB.mp3",
        "/Users/dobbikov/Desktop/djmusic/Redpill-Lunch Time (VIP).mp3",
        "/Users/dobbikov/Desktop/djmusic/Rieger-Butcher.mp3",
        "/Users/dobbikov/Desktop/djmusic/Rusty K-Where Is My Mind (Cover).mp3",
        "/Users/dobbikov/Desktop/djmusic/Scorn   Magnetude.mp3",
        "/Users/dobbikov/Desktop/djmusic/Snatch   Magnetude.mp3",
        "/Users/dobbikov/Desktop/djmusic/State Of Mind-Chain Reaction (feat. Coppa).mp3",
        "/Users/dobbikov/Desktop/djmusic/State_Of_Mind,_Black_Sun_Empire-Bottom_Line.mp3",
        "/Users/dobbikov/Desktop/djmusic/Symplex-Witch.mp3",
        "/Users/dobbikov/Desktop/djmusic/Teddy Killerz-Pie.mp3",
        "/Users/dobbikov/Desktop/djmusic/The_Clamps-Mankind.mp3",
        "/Users/dobbikov/Desktop/djmusic/Tobax, Mean Teeth-Bring the Pain.mp3",
        "/Users/dobbikov/Desktop/djmusic/home manta.mp3",
        "/Users/dobbikov/Desktop/djmusic/hysteria eelun burr oak.mp3",
        "/Users/dobbikov/Desktop/djmusic/receptor - Lullaby Original Mix.mp3",
    ]
    .into_iter()
    .map(|p| std::path::PathBuf::from(p))
    .collect();

    let sorted = analyze_and_sort_tracks(&track_paths, 100);

    let mut num = 1;
    for track in sorted {
        println!("{} | {} | {}", num, track.key().unwrap(), track.name());
        num += 1
    }
}
fn sort_my_old_tracks() {
    set_log_level(Level::DEBUG);
    let tracks = vec![
        Track::from_pair("One - Akov, VEGAS.mp3", "5A"),
        Track::from_pair("Decisions   Phace   Mefjus.mp3", "6A"),
        Track::from_pair("Sovereign - Pythius.mp3", "7A"),
        Track::from_pair("BBT   Pythius.mp3", "7B"),
        Track::from_pair("Sovereign (Neonlight Remix)   Pythius.mp3", "7A"),
        Track::from_pair("Freefall - Despersion feat. 2Whales.mp3", "7A"),
        Track::from_pair("Gydra - Primitive Instinct (Original Mix).mp3", "8A"),
        Track::from_pair("Prophecy - Kanine.mp3", "9A"),
        Track::from_pair("audio.mp3", "9B"),
        Track::from_pair("Mantra   Noisia.mp3", "9B"),
        Track::from_pair("Entracte collapse - Magnetude, KOLT, Misanthr.mp3", "4A"),
        Track::from_pair("Friday - Magnetude.mp3", "4A"),
        Track::from_pair(
            "16_Synergy_Dark_Machine_Original_Mix_Original_Mix_muzzo_ru.mp3",
            "4A",
        ),
        Track::from_pair("Wipe feat. IHR (Original Mix).mp3", "4A"),
        Track::from_pair("Beat Down - Prolix, DC Breaks.mp3", "4A"),
        Track::from_pair("Hammerhead (Original Mix).mp3", "4A"),
        Track::from_pair("Krieg - Qo, The Clamps.mp3", "5A"),
        Track::from_pair("The Broken   Joanna Syze, barbarix.mp3", "12B"),
        Track::from_pair("Dark Days   Joanna Syze x Mizo.mp3", "12A"),
        Track::from_pair("Suspect [Synergy Remix]   Pythius.mp3", "3B"),
        Track::from_pair("Altar - Dimension.mp3", "4B"),
        Track::from_pair("Fire - Murdock, Doctrine.mp3", "4A"),
        Track::from_pair("Dust Devil - Mizo.mp3", "4A"),
        Track::from_pair("Stoning - Gydra.mp3", "4A"),
        Track::from_pair("Dominator - James Marvel, June Miller, MC Mot.mp3", "4A"),
        Track::from_pair("Peace - Despersion.mp3", "5A"),
        Track::from_pair("Joe Ford - Tomb Raver (Original Mix).mp3", "8B"),
        Track::from_pair("Fire   Blood (ABIS Remix)   3RDKND.mp3", "9B"),
        Track::from_pair("Asteroids   Prolix, Noisia.mp3", "9A"),
        Track::from_pair("Forgotten Myths   KOAN Sound.mp3", "9B"),
        Track::from_pair("I m For You   Magnetude.mp3", "9A"),
    ];

    let sorted_tracks = melodic_sort(&tracks, 10000);
    for track in sorted_tracks {
        println!("{} - {}", track.name(), track.key().unwrap())
    }
    println!("Hey")
}
